# Generated by Django 2.2 on 2021-04-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_user',
            fields=[
                ('uname', models.TextField(primary_key=True, serialize=False)),
                ('pwd', models.TextField()),
                ('fullname', models.TextField()),
                ('nip', models.TextField()),
                ('level', models.TextField()),
            ],
            options={
                'db_table': 'master"."master_user',
                'ordering': ['uname'],
                'managed': False,
            },
        ),
    ]
